### ISSUE TITLE
World Bank API

### ISSUE THREAD

**Issue by lennybriscoe** [chrisbrowning/ruby-capitals#2]
World Bank API seems to suit our needs at the moment. There are drawbacks, though. WB omits some small, politically-controversial (WB is a political institution, mindyou) countries from its API. E.g. Taiwan--a nation of 30 something million--is excluded but the Isle of Man--a semi-autonomous territory between Britain and Ireland--is not.

Perhaps other APIs should be looked into...

**Comment by chrisbrowning** [comment]
seems fine
